spring:
  application:
    name: spring100studies

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      format_sql: true
      hibernate:
        show_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html


logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
